# Generated by Django 2.2 on 2020-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181009_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='Isvalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contactno',
            field=models.CharField(max_length=12),
        ),
    ]
